---
- hosts: all
  tasks:

  - name: Check if a service is installed
    win_service:
      name: SNMPTRAP
    register: service_info

  - name: Configure the BITS Service
    win_service:
      name: SNMPTRAP
      state: started
      start_mode: auto
