---
- hosts: all
  vars:
    myfiles:
      - { p: 'c:\temp', 
          f: 'loop-test1', 
          env: 'Prod', 
          domain: 'domain', 
          ext: 'txt',
          dbname: [ 'db1', 'db2' ]
        }
      - { p: 'c:\temp', 
          f: 'loop-test2', 
          env: 'Prod', 
          domain: 'domain', 
          ext: 'txt',
          dbname: [ 'db1', 'db2' ]
        }
    i: files.length
     

  tasks:
  - name: Looping
    set_fact:
       dblist: "{{ dbname | join(',') }}"
    debug:
       msg: "{{ item.p }}\\{{ item.f }}-{{ item.env }}-{{ item.domain}}.{{ item.ext }}"

    loop:
      "{{ myfiles }}"

  - name: Looping nested
    debug:
         msg: "{{ item.0.f }}/{{ item.1 }}"
    with_subelements:
      - "{{ myfiles }}"
      - dbname

  - name: Show extracted list of keys from a list of dictionaries
    debug:
       msg: "{{ chains | map('extract', chains_config) | map(attribute='configs') | flatten | map(attribute='type') | flatten }}"
    vars:
       chains: [1, 2]
       chains_config:
           1:
               foo: bar
               configs:
                   - type: routed
                     version: 0.1
                   - type: bridged
                     version: 0.2
           2:
               foo: baz
               configs:
                   - type: routed
                     version: 1.0
                   - type: bridged
                     version: 1.1


