---
- hosts: all
  tasks:

  - name: Powershell | Install Required Powershell Modules
    win_psmodule:
      name: xActiveDirectory
      state: present

  - name: Create Test Account
    win_dsc:
      resource_name:  xADUser
      DomainName: SQL.com
      UserName: "test_user"
      Ensure: present
      Path: "CN=test_user,OU=SQL Service Accounts,DC=SQL,DC=com"
      DisplayName:  "Test User"
      GivenName:  "Test"
      Surname: "User"
      UserPrincipalName: "test_user@SQL.com"
      Enabled:  true
      PasswordNeverExpires: true
