---
- hosts: all
  vars:
    files:
      - { name: 'c:\temp\loop-test1.txt' }
      - { name: 'c:\temp\loop-test2.txt' }
    i: files.length
     

  tasks:
  - name: Creating an empty file
    win_file:
      path: "{{ item.value }}"
      state: touch
    loop:
      {{ files }}

