---
- hosts: all
  vars:
    files:
      - { name: 'c:\temp\loop-test1.txt', 
          env: 'Prod', 
          domain: 'domain', 
          dbname: { db1: 'db1', db2: 'db2' }
        }
      - { name: 'c:\temp\loop-test2.txt' , 
          env: 'Prod', 
          domain: 'domain', 
          dbname: { db1: 'db1', db2: 'db2' }
        }
    i: files.length
     

  tasks:
  - name: Creating an empty file
    win_file:
      path: "{{ item.name }}"
      state: touch
    loop:
      "{{ files }}"

