---
- hosts: all
  tasks:
  - name: Creating an empty file
    win_file:
      path: "{{ item }}"
      state: touch
    with_items:
    - name: C:\temp\loop-test1.txt"
    - name: C:\temp\loop-test2.txt"

