---
- hosts: all
  vars:
    files:
      - { p: 'c:\temp', 
          f: 'loop-test1', 
          env: 'Prod', 
          domain: 'domain', 
          ext: 'txt',
          dbname: { db1: 'db1', db2: 'db2' }
        }
      - { p: 'c:\temp', 
          f: 'loop-test2', 
          env: 'Prod', 
          domain: 'domain', 
          ext: 'txt',
          dbname: { db1: 'db1', db2: 'db2' }
        }
    i: files.length
     

  tasks:
  - name: Creating an empty file
    win_file:
      path: "{{ item.p }}\{{ item.f }}.{{ item.ext }}"
      path: "{{ item.p }}\{{ item.f }}-{{ item.env }}.{{ item.ext }}"
      path: "{{ item.p }}\{{ item.f }}-{{ item.domain }}.{{ item.ext }}"
      state: touch
    loop:
      "{{ files }}"

