---
- hosts: all
  tasks:
  - name: Creating an empty file
    win_file:
      path: "{{ item.name }}"
      state: touch
    loop:
      - { name: 'c:\temp\loop-test1.txt' }
      - { name: 'c:\temp\loop-test2.txt' }

